### ISSUE TITLE
博主什么时候更新Java8的HashMap

### ISSUE THREAD

**Issue by nl101531** [CarpenterLee/JCFInternals#1]
Java8的HashMap做了相当多的优化,当桶上的链表节点大于8的话就转换为红黑树了,测试在hash极不均匀的情况下相比JDK7有明显的性能提升,等待你的分析博客了

**Comment by CarpenterLee** [comment]
多谢小生的关注，文章中关于红黑树和哈希表都已经讲过，两者结合在一起也不难理解吧，就不展开说了。可参考[JEP 180: Handle Frequent HashMap Collisions with Balanced Trees](http://openjdk.java.net/jeps/180)

**Comment by nl101531** [comment]
好的,感谢博主博文的帮助
