### ISSUE TITLE
5-TreeSet and TreeMap.md

### ISSUE THREAD

**Issue by sd886393** [CarpenterLee/JCFInternals#3]
寻找节点后继
t的右孩子为空，则t的后继是其第一个向左走的祖先。
->
虽然代码是`ch == p.right`  表述是否应换为"第一个向右走的祖先"?

另外 文中所说的情况1~6 是哪些呢?望答主不吝赐教

**Comment by CarpenterLee** [comment]
这里说的“向左”指的是站在父节点的角度来看。
情况1-6指的是红黑树插入新元素之后的调整有6中情况，详见fixAfterInsertion()方法。

**Comment by sd886393** [comment]
好的, 谢谢回复
